### ISSUE TITLE
Add qt5-tools as a make dependency for the aur package

### ISSUE THREAD

**Issue by LechTheMitch** [irfanhakim-as/kde-service-menu-reimage#10]
Thank you for this awesome KDE mod, the installation script for the package call the qtpaths command which is present in the qt5-tools package which isn't a dependency making users think the package is broken, if possible i suggest you add it as a make dependency for a smoother experience

**Comment by irfanhakim-as** [comment]
yea you are right - I meant to do so but forgot about it after considering whether it should be the `qt5` or `qt6` version (verified that it works with either) and what package comes with it (`-tools` or `-base`), I'll check it out later and update it. Thanks for the heads-up!
